###########################################################################
# GitHub Action Workflow
# On assignment of the explicit label `Deploy with CircleCI` to an open PR
# in GitHub this action will trigger a deploy job within CircleCI for the
# branch defined in the given PR.
#
# Step 0: Checkout latest commit on current branch
#
# Step 1: Using the GitHub API make a request to get the latest Status Checks
#         for the current branch. This will be used to ensure that all checks
#         have passed in CircleCI prior to making the deployment
#         Leverages the open source GitHub Action:
#           https://github.com/octokit/request-action
#         Makes a request to the combined status checks API in GitHub
#           https://docs.github.com/en/rest/reference/repos#statuses
#
# Step 2: Extract the combined state from the GitHub API response and store
#         only the state value as an output for future steps
#
# Step 3: If the PR State is `success` make a request to the V2 CircleCI API
#         to initiate the `dev-deployment` workflow for the current branch.
#         Leverages the open source GitHub Action:
#           https://github.com/promiseofcake/circleci-trigger-action
###########################################################################
name: Run Checks based on label
on:
  pull_request:
jobs:
  pr_labeled_deployment:
    runs-on: ubuntu-latest
    name: Initiate checks in circleci
    steps:
    - uses: actions/checkout@v2
    - name: Extract OWASP Label
      id: extract-owasp-label
      if: contains( github.event.pull_request.labels.*.name, 'run-owasp')
      run: |
        echo "::set-output name=OWASP::true"
        
    - name: Extract Frontend Label
      id: extract-owasp-label
      if: contains( github.event.pull_request.labels.*.name, 'run-frontend')
      run: |
        echo "::set-output name=FRONTEND::true"

    - name: Extract Backend Label
      id: extract-owasp-label
      if: contains( github.event.pull_request.labels.*.name, 'run-backend')
      run: |
        echo "::set-output name=BACKEND::true"

    - name: Extract Pa11y Label
      id: extract-owasp-label
      if: contains( github.event.pull_request.labels.*.name, 'run-pa11y')
      run: |
        echo "::set-output name=PA11y::true"

    - name: Extract QASP Label
      id: extract-owasp-label
      if: contains( github.event.pull_request.labels.*.name, 'run-qasp')
      run: |
        echo "::set-output name=PA11Y::true"

    - name: Get PR Status Checks
      id: get-pr-checks
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/{owner}/{repo}/commits/{ref}/status
        owner: ${{ github.repository_owner }}
        repo: TANF-app
        ref: ${{ github.event.pull_request.head.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract current PR state
      id: get-pr-state
      run: |
        STATE=${{ fromJson(steps.get-pr-checks.outputs.data).state }}
        echo "::set-output name=STATE::$STATE"
        echo "Current PR state: $STATE"

    - name: Circle CI checks Trigger
      id: curl-circle-ci
      if: steps.get-pr-state.outputs.STATE == 'success'
      uses: promiseofcake/circleci-trigger-action@v1
      with:
        user-token: ${{ secrets.CIRCLE_CI_V2_API_TOKEN }}
        project-slug: raft-tech/TANF-app
        branch: ${{ github.head_ref }}
        payload: |
          {
            "frontend": '${{steps.extract-frontend-label.outputs.FRONTEND}}',
            "backend": '${{steps.extract-frontend-label.outputs.BACKEND}}',
            "pa11y": '${{steps.extract-pa11y-label.outputs.PA11Y}}',
            "owasp": '${{steps.extract-owasp-label.outputs.OWASP}}',
            "qasp": '${{steps.extract-qasp-label.outputs.QASP}}'
          }

